# Generated by Django 5.2.8 on 2025-11-13 17:01

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LibraryUser",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="0123456789",
                        editable=False,
                        length=6,
                        max_length=6,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=65)),
                ("surename", models.CharField(max_length=65)),
            ],
            options={
                "db_table": "library_user",
            },
        ),
    ]
